version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - PROJECT_GDO_DATABASE_HOST=mysql
      - PROJECT_GDO_DATABASE_USERNAME=root
      - PROJECT_GDO_DATABASE_PASSWORD=root
      - PROJECT_GDO_DATABASE=volei-gdo
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: volei-gdo
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
